apiVersion: apps/v1
kind: Deployment
metadata:
  name: espocrm
  namespace: espocrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espocrm
  template:
    metadata:
      labels:
        app: espocrm
    spec:
      containers:
        - name: espocrm
          image: espocrm/espocrm
          env:
            - name: ESPOCRM_DATABASE_PLATFORM
              value: "Mysql"
            - name: ESPOCRM_DATABASE_HOST
              value: "espocrm-mariadb"
            - name: ESPOCRM_DATABASE_USER
              value: "espocrm"
            - name: ESPOCRM_DATABASE_PASSWORD
              value: "password"
            - name: ESPOCRM_ADMIN_USERNAME
              value: "admin"
            - name: ESPOCRM_ADMIN_PASSWORD
              value: "password"
            - name: ESPOCRM_SITE_URL
              value: "https://espocrm.cloud.clearclean.local"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: espocrm-storage
              mountPath: /var/www/html
      restartPolicy: Always
      volumes:
        - name: espocrm-storage
          persistentVolumeClaim:
            claimName: espocrm-pvc
