apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- traefik-sync.yaml
- espocrm-sync.yaml
- cert-manager-sync.yaml
- cert-manager-config-sync.yaml
